# Makefile

bagtest: bagtest.cpp
	g++ bagtest.cpp -o bagtest
	
keytest: keytest.cpp
	g++ keytest.cpp -o keytest
	
rottest: rottest.cpp
	g++ rottest.cpp -o rottest
	
sigtest: sigtest.cpp
	g++ sigtest.cpp -o sigtest